name: codox

on: [push]

jobs:

  clojure:

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: checkout jvxi11
      - uses: actions/checkout@master
        with:
          name: wactbprot/jvxi11
          ref: refs/heads/release
          path: ./resources

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: compile with Ant
        path: ./resources/jvxi11
        run: |
          ant compile
          ant jar
        
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          cli: 1.10.1.693 
  
      - name: execute codox
        run: clojure -X:dev:codox
        shell: bash

      - name: deploy codox
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      - uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: docs

