name: codox

on: [push]

jobs:

  clojure:

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: checkout jvxi11
        uses: actions/checkout@master
        with:
          repository: wactbprot/jvxi11

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Ant
        run: |
          ant compile
          ant jar
          
      - uses: actions/checkout@master
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "jvxi11/dist/jvxi11.jar"
          target: "resources/jvxi11/dist/jvxi11.jar"

                    
      - uses: actions/checkout@master
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "jvxi11/external/oncrpc.jar"
          target: "resources/jvxi11/external/oncrpc.jar"

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          # Install just one or all simultaneously
          cli: 1.10.1.693 # Clojure CLI based on tools.deps
  
      - name: execute codox
        run: clojure -X:dev:codox
        shell: bash

      - name: deploy codox
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      - uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: docs

